const faTextConstant = {
    name: "فیدیبو",
    searchPlaceholder: "جستجو",
    loginSignup: "ورود / ثبت‌نام",
    downloadApp: "دانلود اپلیکیشن",
    home: "خانه",
    audioTextBooks: "کتاب‌های صوتی و متنی",
    podcasts: "پادکست‌ها",
    magazines: "مجله",
    fidiPlus: "فیدی‌پلاس",
    author: "نویسنده",
    authors: "نویسندگان",
    publisher: "ناشر",
    publishers: "ناشران",
    withoutComment: "بدون نظر",
    currency: "تومان",
    buy: "خرید",
    borrow: "امانت‌گرفتن از فیدی‌پلاس",
    getExample: "دریافت نمونه",
    readExample: "خواندن نمونه",
    placeThisTitle: "گذاشتن این عنوان در...",
    myShelf: "قفسه‌های من",
    myBookmarks: "نشان‌شده‌ها",
    myReads: "مطالعه‌شده‌ها",
    showComplete: "توضیحات کامل",
    showLess: "نمایش کوتاه‌تر",
    categoriesTitle: "دسته‌ها:",
    tagsTitle: "کلیدواژه‌های مرتبط:",
    bookEditions: "نسخه‌های دیگر از همین اثر",
}

export default faTextConstant