const FLEX_TYPES = {
    NEW_FLEX_BOOK_INTRODUCTION: "NEW_FLEX_BOOK_INTRODUCTION",
    VL_TEXT_ROWS: "VL_TEXT_ROWS",
    NEW_FLEX_BOOK_LIBRARY: "NEW_FLEX_BOOK_LIBRARY",
    NEW_FLEX_BOOK_EDITIONS: "NEW_FLEX_BOOK_EDITIONS",
}

export default FLEX_TYPES